## Basics of Numpy

In [5]:
import numpy as np

In [6]:
#create a single dimension array
a=np.array([1,2,3,5,6,7,8])

In [7]:
print(a)

[1 2 3 5 6 7 8]


In [8]:
a[3]

5

In [9]:
type(a)

numpy.ndarray

In [10]:
#create multidimension array
b=np.array([(1,2,3,5,6,4),(2,3,4,5,6,2),(7,3,1,10,23)])

In [12]:
print(b)

[(1, 2, 3, 5, 6, 4) (2, 3, 4, 5, 6, 2) (7, 3, 1, 10, 23)]


In [13]:
type(b)

numpy.ndarray

In [14]:
c=np.array([(1,2,3,4),(4,5,6,4)])

In [15]:
c

array([[1, 2, 3, 4],
       [4, 5, 6, 4]])

In [16]:
c.ndim

2

In [18]:
b.ndim

1

In [19]:
c.itemsize

4

In [20]:
c.dtype

dtype('int32')

In [21]:
d=np.array([(1,2,3),(3,4,5),(1,2,4),(4,5,6),(2,4,5)])

In [22]:
d

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 4],
       [4, 5, 6],
       [2, 4, 5]])

In [23]:
d.ndim

2

In [24]:
d.shape

(5, 3)

In [25]:
d

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 4],
       [4, 5, 6],
       [2, 4, 5]])

In [26]:
d[2]

array([1, 2, 4])

In [27]:
d[1]

array([3, 4, 5])

In [28]:
d[1,1]

4

In [29]:
d[1,2]

5

In [30]:
d[0:4,1]

array([2, 4, 2, 5])

In [31]:
e=np.array([[(1,2,3),(4,5,6)],[(1,2,3),(4,5,6)]])

In [32]:
e

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [33]:
e.ndim

3

In [34]:
numbers=np.linspace(1,50,20)

In [35]:
numbers

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

In [36]:
numbers.min()

1.0

In [37]:
numbers.max()

50.0

In [38]:
numbers.sum()

510.0

In [39]:
numbers.mean()

25.5

In [40]:
g=np.array([(1,2,4),(2,3,6)])

In [41]:
g

array([[1, 2, 4],
       [2, 3, 6]])

In [42]:
g.sum()

18

In [43]:
g.sum(axis=0)

array([ 3,  5, 10])

In [44]:
g.sum(axis=1)

array([ 7, 11])

In [45]:
#cocatination of arrays
#verticle stacking
#horizontal stacking

In [46]:
i = np.array([(1,2,4),(4,5,6)])
j = np.array([(10,20,40),(40,50,60)])

In [47]:
# vertical stacking
np.vstack((i,j))

array([[ 1,  2,  4],
       [ 4,  5,  6],
       [10, 20, 40],
       [40, 50, 60]])

In [48]:
# horizontal stacking
np.hstack((i,j))

array([[ 1,  2,  4, 10, 20, 40],
       [ 4,  5,  6, 40, 50, 60]])

In [49]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
np.ones((5,5))*200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

In [52]:
np.random.randint(0,100)

4

In [53]:
np.random.randint(0,100,10)

array([13, 74,  1,  3, 40, 33, 75, 47, 14, 20])

In [54]:
np.random.seed(100)
np.random.randint(0,100,10)

array([ 8, 24, 67, 87, 79, 48, 10, 94, 52, 98])

In [55]:
import numpy as np

In [56]:
a = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])

In [57]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [58]:
a.ndim

3